{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "14158f72-0217-4caa-84fa-3367e8bdfc64",
   "metadata": {},
   "outputs": [
    {
     "ename": "ForbiddenError",
     "evalue": "250001 (08001): Failed to connect to DB. Verify the account name is correct: ZQ63941t.snowflakecomputing.com:443. HTTP 403: Forbidden",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mForbiddenError\u001b[0m                            Traceback (most recent call last)",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\snowflake\\connector\\auth\\_auth.py:250\u001b[0m, in \u001b[0;36mAuth.authenticate\u001b[1;34m(self, auth_instance, account, user, database, schema, warehouse, role, passcode, passcode_in_password, mfa_callback, password_callback, session_parameters, timeout)\u001b[0m\n\u001b[0;32m    249\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 250\u001b[0m     ret \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_rest\u001b[38;5;241m.\u001b[39m_post_request(\n\u001b[0;32m    251\u001b[0m         url,\n\u001b[0;32m    252\u001b[0m         headers,\n\u001b[0;32m    253\u001b[0m         json\u001b[38;5;241m.\u001b[39mdumps(body),\n\u001b[0;32m    254\u001b[0m         socket_timeout\u001b[38;5;241m=\u001b[39mauth_instance\u001b[38;5;241m.\u001b[39m_socket_timeout,\n\u001b[0;32m    255\u001b[0m     )\n\u001b[0;32m    256\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m ForbiddenError \u001b[38;5;28;01mas\u001b[39;00m err:\n\u001b[0;32m    257\u001b[0m     \u001b[38;5;66;03m# HTTP 403\u001b[39;00m\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\snowflake\\connector\\network.py:734\u001b[0m, in \u001b[0;36mSnowflakeRestful._post_request\u001b[1;34m(self, url, headers, body, token, timeout, socket_timeout, _no_results, no_retry, _include_retry_params)\u001b[0m\n\u001b[0;32m    732\u001b[0m     pprint(ret)\n\u001b[1;32m--> 734\u001b[0m ret \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mfetch(\n\u001b[0;32m    735\u001b[0m     \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mpost\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[0;32m    736\u001b[0m     full_url,\n\u001b[0;32m    737\u001b[0m     headers,\n\u001b[0;32m    738\u001b[0m     data\u001b[38;5;241m=\u001b[39mbody,\n\u001b[0;32m    739\u001b[0m     timeout\u001b[38;5;241m=\u001b[39mtimeout,\n\u001b[0;32m    740\u001b[0m     token\u001b[38;5;241m=\u001b[39mtoken,\n\u001b[0;32m    741\u001b[0m     no_retry\u001b[38;5;241m=\u001b[39mno_retry,\n\u001b[0;32m    742\u001b[0m     _include_retry_params\u001b[38;5;241m=\u001b[39m_include_retry_params,\n\u001b[0;32m    743\u001b[0m     socket_timeout\u001b[38;5;241m=\u001b[39msocket_timeout,\n\u001b[0;32m    744\u001b[0m )\n\u001b[0;32m    745\u001b[0m logger\u001b[38;5;241m.\u001b[39mdebug(\n\u001b[0;32m    746\u001b[0m     \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mret[code] = \u001b[39m\u001b[38;5;132;01m{code}\u001b[39;00m\u001b[38;5;124m, after post request\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;241m.\u001b[39mformat(\n\u001b[0;32m    747\u001b[0m         code\u001b[38;5;241m=\u001b[39m(ret\u001b[38;5;241m.\u001b[39mget(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mcode\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mN/A\u001b[39m\u001b[38;5;124m\"\u001b[39m))\n\u001b[0;32m    748\u001b[0m     )\n\u001b[0;32m    749\u001b[0m )\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\snowflake\\connector\\network.py:843\u001b[0m, in \u001b[0;36mSnowflakeRestful.fetch\u001b[1;34m(self, method, full_url, headers, data, timeout, **kwargs)\u001b[0m\n\u001b[0;32m    842\u001b[0m \u001b[38;5;28;01mwhile\u001b[39;00m \u001b[38;5;28;01mTrue\u001b[39;00m:\n\u001b[1;32m--> 843\u001b[0m     ret \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_request_exec_wrapper(\n\u001b[0;32m    844\u001b[0m         session, method, full_url, headers, data, retry_ctx, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs\n\u001b[0;32m    845\u001b[0m     )\n\u001b[0;32m    846\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m ret \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\snowflake\\connector\\network.py:979\u001b[0m, in \u001b[0;36mSnowflakeRestful._request_exec_wrapper\u001b[1;34m(self, session, method, full_url, headers, data, retry_ctx, no_retry, token, **kwargs)\u001b[0m\n\u001b[0;32m    978\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m no_retry:\n\u001b[1;32m--> 979\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m e\n\u001b[0;32m    980\u001b[0m logger\u001b[38;5;241m.\u001b[39mdebug(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mIgnored error\u001b[39m\u001b[38;5;124m\"\u001b[39m, exc_info\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mTrue\u001b[39;00m)\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\snowflake\\connector\\network.py:884\u001b[0m, in \u001b[0;36mSnowflakeRestful._request_exec_wrapper\u001b[1;34m(self, session, method, full_url, headers, data, retry_ctx, no_retry, token, **kwargs)\u001b[0m\n\u001b[0;32m    883\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 884\u001b[0m     return_object \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_request_exec(\n\u001b[0;32m    885\u001b[0m         session\u001b[38;5;241m=\u001b[39msession,\n\u001b[0;32m    886\u001b[0m         method\u001b[38;5;241m=\u001b[39mmethod,\n\u001b[0;32m    887\u001b[0m         full_url\u001b[38;5;241m=\u001b[39mfull_url,\n\u001b[0;32m    888\u001b[0m         headers\u001b[38;5;241m=\u001b[39mheaders,\n\u001b[0;32m    889\u001b[0m         data\u001b[38;5;241m=\u001b[39mdata,\n\u001b[0;32m    890\u001b[0m         token\u001b[38;5;241m=\u001b[39mtoken,\n\u001b[0;32m    891\u001b[0m         \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs,\n\u001b[0;32m    892\u001b[0m     )\n\u001b[0;32m    893\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m return_object \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\snowflake\\connector\\network.py:1193\u001b[0m, in \u001b[0;36mSnowflakeRestful._request_exec\u001b[1;34m(self, session, method, full_url, headers, data, token, catch_okta_unauthorized_error, is_raw_text, is_raw_binary, binary_data_handler, socket_timeout, is_okta_authentication)\u001b[0m\n\u001b[0;32m   1184\u001b[0m TelemetryService\u001b[38;5;241m.\u001b[39mget_instance()\u001b[38;5;241m.\u001b[39mlog_http_request_error(\n\u001b[0;32m   1185\u001b[0m     \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mHttpException\u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;241m%\u001b[39m \u001b[38;5;28mstr\u001b[39m(err),\n\u001b[0;32m   1186\u001b[0m     full_url,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m   1191\u001b[0m     stack_trace\u001b[38;5;241m=\u001b[39mtraceback\u001b[38;5;241m.\u001b[39mformat_exc(),\n\u001b[0;32m   1192\u001b[0m )\n\u001b[1;32m-> 1193\u001b[0m \u001b[38;5;28;01mraise\u001b[39;00m err\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\snowflake\\connector\\network.py:1104\u001b[0m, in \u001b[0;36mSnowflakeRestful._request_exec\u001b[1;34m(self, session, method, full_url, headers, data, token, catch_okta_unauthorized_error, is_raw_text, is_raw_binary, binary_data_handler, socket_timeout, is_okta_authentication)\u001b[0m\n\u001b[0;32m   1103\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m is_login_request(full_url) \u001b[38;5;129;01mand\u001b[39;00m raw_ret\u001b[38;5;241m.\u001b[39mstatus_code \u001b[38;5;241m==\u001b[39m FORBIDDEN:\n\u001b[1;32m-> 1104\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m ForbiddenError\n\u001b[0;32m   1106\u001b[0m \u001b[38;5;28;01melif\u001b[39;00m is_retryable_http_code(raw_ret\u001b[38;5;241m.\u001b[39mstatus_code):\n",
      "\u001b[1;31mForbiddenError\u001b[0m: HTTP 403: Forbidden",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mForbiddenError\u001b[0m                            Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[5], line 10\u001b[0m\n\u001b[0;32m      7\u001b[0m mongo_collection \u001b[38;5;241m=\u001b[39m mongo_db[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124muserdatas\u001b[39m\u001b[38;5;124m'\u001b[39m]\n\u001b[0;32m      9\u001b[0m \u001b[38;5;66;03m# Connect to Snowflake\u001b[39;00m\n\u001b[1;32m---> 10\u001b[0m snowflake_conn \u001b[38;5;241m=\u001b[39m snowflake\u001b[38;5;241m.\u001b[39mconnector\u001b[38;5;241m.\u001b[39mconnect(\n\u001b[0;32m     11\u001b[0m     user\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mkaustubh\u001b[39m\u001b[38;5;124m'\u001b[39m,\n\u001b[0;32m     12\u001b[0m     password\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m@@Kaustubh123\u001b[39m\u001b[38;5;124m'\u001b[39m,\n\u001b[0;32m     13\u001b[0m     account\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mZQ63941t\u001b[39m\u001b[38;5;124m'\u001b[39m,\n\u001b[0;32m     14\u001b[0m     warehouse\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mMAINPROJECT\u001b[39m\u001b[38;5;124m'\u001b[39m,\n\u001b[0;32m     15\u001b[0m     database\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mMAIN_PROJECT\u001b[39m\u001b[38;5;124m'\u001b[39m,\n\u001b[0;32m     16\u001b[0m     schema\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mUSERSDATA\u001b[39m\u001b[38;5;124m'\u001b[39m\n\u001b[0;32m     17\u001b[0m )\n\u001b[0;32m     19\u001b[0m \u001b[38;5;66;03m# Snowflake table creation SQL\u001b[39;00m\n\u001b[0;32m     20\u001b[0m create_table_sql \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m\"\"\"\u001b[39m\n\u001b[0;32m     21\u001b[0m \u001b[38;5;124mCREATE TABLE IF NOT EXISTS your_snowflake_table (\u001b[39m\n\u001b[0;32m     22\u001b[0m \u001b[38;5;124m    field1 datatype,\u001b[39m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m     25\u001b[0m \u001b[38;5;124m);\u001b[39m\n\u001b[0;32m     26\u001b[0m \u001b[38;5;124m\"\"\"\u001b[39m\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\snowflake\\connector\\__init__.py:54\u001b[0m, in \u001b[0;36mConnect\u001b[1;34m(**kwargs)\u001b[0m\n\u001b[0;32m     52\u001b[0m \u001b[38;5;129m@wraps\u001b[39m(SnowflakeConnection\u001b[38;5;241m.\u001b[39m\u001b[38;5;21m__init__\u001b[39m)\n\u001b[0;32m     53\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mConnect\u001b[39m(\u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m SnowflakeConnection:\n\u001b[1;32m---> 54\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m SnowflakeConnection(\u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\snowflake\\connector\\connection.py:429\u001b[0m, in \u001b[0;36mSnowflakeConnection.__init__\u001b[1;34m(self, connection_name, connections_file_path, **kwargs)\u001b[0m\n\u001b[0;32m    427\u001b[0m     kwargs \u001b[38;5;241m=\u001b[39m _get_default_connection_params()\n\u001b[0;32m    428\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m__set_error_attributes()\n\u001b[1;32m--> 429\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mconnect(\u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n\u001b[0;32m    430\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_telemetry \u001b[38;5;241m=\u001b[39m TelemetryClient(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_rest)\n\u001b[0;32m    431\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mexpired \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mFalse\u001b[39;00m\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\snowflake\\connector\\connection.py:719\u001b[0m, in \u001b[0;36mSnowflakeConnection.connect\u001b[1;34m(self, **kwargs)\u001b[0m\n\u001b[0;32m    717\u001b[0m             \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m(\u001b[38;5;28mstr\u001b[39m(exceptions_dict))\n\u001b[0;32m    718\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m--> 719\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m__open_connection()\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\snowflake\\connector\\connection.py:1045\u001b[0m, in \u001b[0;36mSnowflakeConnection.__open_connection\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m   1037\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m   1038\u001b[0m     \u001b[38;5;66;03m# okta URL, e.g., https://<account>.okta.com/\u001b[39;00m\n\u001b[0;32m   1039\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mauth_class \u001b[38;5;241m=\u001b[39m AuthByOkta(\n\u001b[0;32m   1040\u001b[0m         application\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mapplication,\n\u001b[0;32m   1041\u001b[0m         timeout\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_login_timeout,\n\u001b[0;32m   1042\u001b[0m         backoff_generator\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_backoff_generator,\n\u001b[0;32m   1043\u001b[0m     )\n\u001b[1;32m-> 1045\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mauthenticate_with_retry(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mauth_class)\n\u001b[0;32m   1047\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_password \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m  \u001b[38;5;66;03m# ensure password won't persist\u001b[39;00m\n\u001b[0;32m   1048\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mauth_class\u001b[38;5;241m.\u001b[39mreset_secrets()\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\snowflake\\connector\\connection.py:1317\u001b[0m, in \u001b[0;36mSnowflakeConnection.authenticate_with_retry\u001b[1;34m(self, auth_instance)\u001b[0m\n\u001b[0;32m   1314\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mauthenticate_with_retry\u001b[39m(\u001b[38;5;28mself\u001b[39m, auth_instance) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[0;32m   1315\u001b[0m     \u001b[38;5;66;03m# make some changes if needed before real __authenticate\u001b[39;00m\n\u001b[0;32m   1316\u001b[0m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m-> 1317\u001b[0m         \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_authenticate(auth_instance)\n\u001b[0;32m   1318\u001b[0m     \u001b[38;5;28;01mexcept\u001b[39;00m ReauthenticationRequest \u001b[38;5;28;01mas\u001b[39;00m ex:\n\u001b[0;32m   1319\u001b[0m         \u001b[38;5;66;03m# cached id_token expiration error, we have cleaned id_token and try to authenticate again\u001b[39;00m\n\u001b[0;32m   1320\u001b[0m         logger\u001b[38;5;241m.\u001b[39mdebug(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mID token expired. Reauthenticating...: \u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m\"\u001b[39m, ex)\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\snowflake\\connector\\connection.py:1345\u001b[0m, in \u001b[0;36mSnowflakeConnection._authenticate\u001b[1;34m(self, auth_instance)\u001b[0m\n\u001b[0;32m   1343\u001b[0m auth_instance\u001b[38;5;241m.\u001b[39m_retry_ctx\u001b[38;5;241m.\u001b[39mset_start_time()\n\u001b[0;32m   1344\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m-> 1345\u001b[0m     auth\u001b[38;5;241m.\u001b[39mauthenticate(\n\u001b[0;32m   1346\u001b[0m         auth_instance\u001b[38;5;241m=\u001b[39mauth_instance,\n\u001b[0;32m   1347\u001b[0m         account\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39maccount,\n\u001b[0;32m   1348\u001b[0m         user\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39muser,\n\u001b[0;32m   1349\u001b[0m         database\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdatabase,\n\u001b[0;32m   1350\u001b[0m         schema\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mschema,\n\u001b[0;32m   1351\u001b[0m         warehouse\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mwarehouse,\n\u001b[0;32m   1352\u001b[0m         role\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mrole,\n\u001b[0;32m   1353\u001b[0m         passcode\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_passcode,\n\u001b[0;32m   1354\u001b[0m         passcode_in_password\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_passcode_in_password,\n\u001b[0;32m   1355\u001b[0m         mfa_callback\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_mfa_callback,\n\u001b[0;32m   1356\u001b[0m         password_callback\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_password_callback,\n\u001b[0;32m   1357\u001b[0m         session_parameters\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_session_parameters,\n\u001b[0;32m   1358\u001b[0m     )\n\u001b[0;32m   1359\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m OperationalError \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[0;32m   1360\u001b[0m     logger\u001b[38;5;241m.\u001b[39mdebug(\n\u001b[0;32m   1361\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mOperational Error raised at authentication\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m   1362\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mfor authenticator: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mtype\u001b[39m(auth_instance)\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m   1363\u001b[0m     )\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\snowflake\\connector\\auth\\_auth.py:258\u001b[0m, in \u001b[0;36mAuth.authenticate\u001b[1;34m(self, auth_instance, account, user, database, schema, warehouse, role, passcode, passcode_in_password, mfa_callback, password_callback, session_parameters, timeout)\u001b[0m\n\u001b[0;32m    250\u001b[0m     ret \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_rest\u001b[38;5;241m.\u001b[39m_post_request(\n\u001b[0;32m    251\u001b[0m         url,\n\u001b[0;32m    252\u001b[0m         headers,\n\u001b[0;32m    253\u001b[0m         json\u001b[38;5;241m.\u001b[39mdumps(body),\n\u001b[0;32m    254\u001b[0m         socket_timeout\u001b[38;5;241m=\u001b[39mauth_instance\u001b[38;5;241m.\u001b[39m_socket_timeout,\n\u001b[0;32m    255\u001b[0m     )\n\u001b[0;32m    256\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m ForbiddenError \u001b[38;5;28;01mas\u001b[39;00m err:\n\u001b[0;32m    257\u001b[0m     \u001b[38;5;66;03m# HTTP 403\u001b[39;00m\n\u001b[1;32m--> 258\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m err\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__class__\u001b[39m(\n\u001b[0;32m    259\u001b[0m         msg\u001b[38;5;241m=\u001b[39m(\n\u001b[0;32m    260\u001b[0m             \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mFailed to connect to DB. \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    261\u001b[0m             \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mVerify the account name is correct: \u001b[39m\u001b[38;5;132;01m{host}\u001b[39;00m\u001b[38;5;124m:\u001b[39m\u001b[38;5;132;01m{port}\u001b[39;00m\u001b[38;5;124m. \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    262\u001b[0m             \u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{message}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    263\u001b[0m         )\u001b[38;5;241m.\u001b[39mformat(\n\u001b[0;32m    264\u001b[0m             host\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_rest\u001b[38;5;241m.\u001b[39m_host, port\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_rest\u001b[38;5;241m.\u001b[39m_port, message\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mstr\u001b[39m(err)\n\u001b[0;32m    265\u001b[0m         ),\n\u001b[0;32m    266\u001b[0m         errno\u001b[38;5;241m=\u001b[39mER_FAILED_TO_CONNECT_TO_DB,\n\u001b[0;32m    267\u001b[0m         sqlstate\u001b[38;5;241m=\u001b[39mSQLSTATE_CONNECTION_WAS_NOT_ESTABLISHED,\n\u001b[0;32m    268\u001b[0m     )\n\u001b[0;32m    269\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m (ServiceUnavailableError, BadGatewayError) \u001b[38;5;28;01mas\u001b[39;00m err:\n\u001b[0;32m    270\u001b[0m     \u001b[38;5;66;03m# HTTP 502/504\u001b[39;00m\n\u001b[0;32m    271\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m err\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__class__\u001b[39m(\n\u001b[0;32m    272\u001b[0m         msg\u001b[38;5;241m=\u001b[39m(\n\u001b[0;32m    273\u001b[0m             \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mFailed to connect to DB. \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    280\u001b[0m         sqlstate\u001b[38;5;241m=\u001b[39mSQLSTATE_CONNECTION_WAS_NOT_ESTABLISHED,\n\u001b[0;32m    281\u001b[0m     )\n",
      "\u001b[1;31mForbiddenError\u001b[0m: 250001 (08001): Failed to connect to DB. Verify the account name is correct: ZQ63941t.snowflakecomputing.com:443. HTTP 403: Forbidden"
     ]
    }
   ],
   "source": [
    "from pymongo import MongoClient\n",
    "import snowflake.connector\n",
    "\n",
    "# Connect to MongoDB\n",
    "mongo_client = MongoClient('mongodb://localhost:3001/')\n",
    "mongo_db = mongo_client['MAINPROJECT']\n",
    "mongo_collection = mongo_db['userdatas']\n",
    "\n",
    "# Connect to Snowflake\n",
    "snowflake_conn = snowflake.connector.connect(\n",
    "    user='kaustubh',\n",
    "    password='@@Kaustubh123',\n",
    "    account='ZQ63941t',\n",
    "    warehouse='MAINPROJECT',\n",
    "    database='MAIN_PROJECT',\n",
    "    schema='USERSDATA'\n",
    ")\n",
    "\n",
    "# Snowflake table creation SQL\n",
    "create_table_sql = \"\"\"\n",
    "CREATE TABLE IF NOT EXISTS your_snowflake_table (\n",
    "    field1 datatype,\n",
    "    field2 datatype,\n",
    "    -- Add more columns as needed\n",
    ");\n",
    "\"\"\"\n",
    "\n",
    "# Insert data into Snowflake\n",
    "def insert_into_snowflake(doc):\n",
    "    cur = snowflake_conn.cursor()\n",
    "    cur.execute(\"INSERT INTO your_snowflake_table VALUES (?, ?)\", (doc['field1'], doc['field2']))\n",
    "    cur.close()\n",
    "\n",
    "# Create Snowflake table if it doesn't exist\n",
    "cur = snowflake_conn.cursor()\n",
    "cur.execute(create_table_sql)\n",
    "cur.close()\n",
    "\n",
    "# Watch for changes in MongoDB\n",
    "with mongo_collection.watch() as stream:\n",
    "    for change in stream:\n",
    "        if change['operationType'] == 'insert':\n",
    "            # Handle insert operation\n",
    "            document = change['fullDocument']\n",
    "            insert_into_snowflake(document)\n",
    "        elif change['operationType'] == 'update':\n",
    "            # Handle update operation\n",
    "            # Note: You may need to implement logic based on your use case\n",
    "            pass\n",
    "        elif change['operationType'] == 'delete':\n",
    "            # Handle delete operation\n",
    "            # Note: You may need to implement logic based on your use case\n",
    "            pass\n",
    "\n",
    "# Close connections\n",
    "mongo_client.close()\n",
    "snowflake_conn.close()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "560b6b51-84a2-4e71-a45b-d859165cf968",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting pymongo\n",
      "  Downloading pymongo-4.6.3-cp311-cp311-win_amd64.whl.metadata (22 kB)\n",
      "Collecting dnspython<3.0.0,>=1.16.0 (from pymongo)\n",
      "  Downloading dnspython-2.6.1-py3-none-any.whl.metadata (5.8 kB)\n",
      "Downloading pymongo-4.6.3-cp311-cp311-win_amd64.whl (472 kB)\n",
      "   ---------------------------------------- 0.0/472.9 kB ? eta -:--:--\n",
      "   -- ------------------------------------ 30.7/472.9 kB 660.6 kB/s eta 0:00:01\n",
      "   --- ----------------------------------- 41.0/472.9 kB 667.8 kB/s eta 0:00:01\n",
      "   ---------------- ----------------------- 194.6/472.9 kB 1.5 MB/s eta 0:00:01\n",
      "   ----------------------- ---------------- 276.5/472.9 kB 1.6 MB/s eta 0:00:01\n",
      "   ------------------------------- -------- 368.6/472.9 kB 1.6 MB/s eta 0:00:01\n",
      "   -------------------------------------- - 450.6/472.9 kB 1.7 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 472.9/472.9 kB 1.6 MB/s eta 0:00:00\n",
      "Downloading dnspython-2.6.1-py3-none-any.whl (307 kB)\n",
      "   ---------------------------------------- 0.0/307.7 kB ? eta -:--:--\n",
      "   ----------- ---------------------------- 92.2/307.7 kB 2.6 MB/s eta 0:00:01\n",
      "   ------------------------- -------------- 194.6/307.7 kB 2.4 MB/s eta 0:00:01\n",
      "   ------------------------------------- -- 286.7/307.7 kB 2.2 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 307.7/307.7 kB 1.9 MB/s eta 0:00:00\n",
      "Installing collected packages: dnspython, pymongo\n",
      "Successfully installed dnspython-2.6.1 pymongo-4.6.3\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install pymongo"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "c5d41d82-600d-4782-91ac-0209e9cf02b4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting snowflake\n",
      "  Downloading snowflake-0.7.0-py3-none-any.whl.metadata (1.9 kB)\n",
      "Collecting snowflake-core==0.7.0 (from snowflake)\n",
      "  Downloading snowflake_core-0.7.0-py3-none-any.whl.metadata (1.8 kB)\n",
      "Collecting snowflake-legacy (from snowflake)\n",
      "  Downloading snowflake_legacy-0.7.0-py3-none-any.whl.metadata (2.5 kB)\n",
      "Collecting atpublic>=4 (from snowflake-core==0.7.0->snowflake)\n",
      "  Downloading atpublic-4.1.0-py3-none-any.whl.metadata (1.8 kB)\n",
      "Requirement already satisfied: pydantic>=1.10.7 in c:\\users\\kaustubhgupta\\anaconda3\\lib\\site-packages (from snowflake-core==0.7.0->snowflake) (1.10.12)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\users\\kaustubhgupta\\anaconda3\\lib\\site-packages (from snowflake-core==0.7.0->snowflake) (2.8.2)\n",
      "Collecting snowflake-snowpark-python<2.0.0,>=1.5.0 (from snowflake-core==0.7.0->snowflake)\n",
      "  Downloading snowflake_snowpark_python-1.14.0-py3-none-any.whl.metadata (55 kB)\n",
      "     ---------------------------------------- 0.0/55.5 kB ? eta -:--:--\n",
      "     ------- -------------------------------- 10.2/55.5 kB ? eta -:--:--\n",
      "     --------------------- ---------------- 30.7/55.5 kB 435.7 kB/s eta 0:00:01\n",
      "     -------------------------------------- 55.5/55.5 kB 415.2 kB/s eta 0:00:00\n",
      "Requirement already satisfied: urllib3 in c:\\users\\kaustubhgupta\\anaconda3\\lib\\site-packages (from snowflake-core==0.7.0->snowflake) (2.0.7)\n",
      "Requirement already satisfied: typing-extensions>=4.2.0 in c:\\users\\kaustubhgupta\\anaconda3\\lib\\site-packages (from pydantic>=1.10.7->snowflake-core==0.7.0->snowflake) (4.9.0)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\kaustubhgupta\\anaconda3\\lib\\site-packages (from python-dateutil>=2.8.2->snowflake-core==0.7.0->snowflake) (1.16.0)\n",
      "Requirement already satisfied: setuptools>=40.6.0 in c:\\users\\kaustubhgupta\\anaconda3\\lib\\site-packages (from snowflake-snowpark-python<2.0.0,>=1.5.0->snowflake-core==0.7.0->snowflake) (68.2.2)\n",
      "Requirement already satisfied: wheel in c:\\users\\kaustubhgupta\\anaconda3\\lib\\site-packages (from snowflake-snowpark-python<2.0.0,>=1.5.0->snowflake-core==0.7.0->snowflake) (0.41.2)\n",
      "Collecting snowflake-connector-python<4.0.0,>=3.6.0 (from snowflake-snowpark-python<2.0.0,>=1.5.0->snowflake-core==0.7.0->snowflake)\n",
      "  Downloading snowflake_connector_python-3.7.1-cp311-cp311-win_amd64.whl.metadata (61 kB)\n",
      "     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--\n",
      "     ---------------------------------------- 61.2/61.2 kB 1.6 MB/s eta 0:00:00\n",
      "Requirement already satisfied: pyyaml in c:\\users\\kaustubhgupta\\anaconda3\\lib\\site-packages (from snowflake-snowpark-python<2.0.0,>=1.5.0->snowflake-core==0.7.0->snowflake) (6.0.1)\n",
      "Requirement already satisfied: cloudpickle==2.2.1 in c:\\users\\kaustubhgupta\\anaconda3\\lib\\site-packages (from snowflake-snowpark-python<2.0.0,>=1.5.0->snowflake-core==0.7.0->snowflake) (2.2.1)\n",
      "Collecting asn1crypto<2.0.0,>0.24.0 (from snowflake-connector-python<4.0.0,>=3.6.0->snowflake-snowpark-python<2.0.0,>=1.5.0->snowflake-core==0.7.0->snowflake)\n",
      "  Downloading asn1crypto-1.5.1-py2.py3-none-any.whl.metadata (13 kB)\n",
      "Requirement already satisfied: cffi<2.0.0,>=1.9 in c:\\users\\kaustubhgupta\\anaconda3\\lib\\site-packages (from snowflake-connector-python<4.0.0,>=3.6.0->snowflake-snowpark-python<2.0.0,>=1.5.0->snowflake-core==0.7.0->snowflake) (1.16.0)\n",
      "Requirement already satisfied: cryptography<43.0.0,>=3.1.0 in c:\\users\\kaustubhgupta\\anaconda3\\lib\\site-packages (from snowflake-connector-python<4.0.0,>=3.6.0->snowflake-snowpark-python<2.0.0,>=1.5.0->snowflake-core==0.7.0->snowflake) (42.0.2)\n",
      "Requirement already satisfied: pyOpenSSL<25.0.0,>=16.2.0 in c:\\users\\kaustubhgupta\\anaconda3\\lib\\site-packages (from snowflake-connector-python<4.0.0,>=3.6.0->snowflake-snowpark-python<2.0.0,>=1.5.0->snowflake-core==0.7.0->snowflake) (24.0.0)\n",
      "Requirement already satisfied: pyjwt<3.0.0 in c:\\users\\kaustubhgupta\\anaconda3\\lib\\site-packages (from snowflake-connector-python<4.0.0,>=3.6.0->snowflake-snowpark-python<2.0.0,>=1.5.0->snowflake-core==0.7.0->snowflake) (2.4.0)\n",
      "Requirement already satisfied: pytz in c:\\users\\kaustubhgupta\\anaconda3\\lib\\site-packages (from snowflake-connector-python<4.0.0,>=3.6.0->snowflake-snowpark-python<2.0.0,>=1.5.0->snowflake-core==0.7.0->snowflake) (2023.3.post1)\n",
      "Requirement already satisfied: requests<3.0.0 in c:\\users\\kaustubhgupta\\anaconda3\\lib\\site-packages (from snowflake-connector-python<4.0.0,>=3.6.0->snowflake-snowpark-python<2.0.0,>=1.5.0->snowflake-core==0.7.0->snowflake) (2.31.0)\n",
      "Requirement already satisfied: packaging in c:\\users\\kaustubhgupta\\anaconda3\\lib\\site-packages (from snowflake-connector-python<4.0.0,>=3.6.0->snowflake-snowpark-python<2.0.0,>=1.5.0->snowflake-core==0.7.0->snowflake) (23.1)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\kaustubhgupta\\anaconda3\\lib\\site-packages (from snowflake-connector-python<4.0.0,>=3.6.0->snowflake-snowpark-python<2.0.0,>=1.5.0->snowflake-core==0.7.0->snowflake) (2.0.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\kaustubhgupta\\anaconda3\\lib\\site-packages (from snowflake-connector-python<4.0.0,>=3.6.0->snowflake-snowpark-python<2.0.0,>=1.5.0->snowflake-core==0.7.0->snowflake) (3.4)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\kaustubhgupta\\anaconda3\\lib\\site-packages (from snowflake-connector-python<4.0.0,>=3.6.0->snowflake-snowpark-python<2.0.0,>=1.5.0->snowflake-core==0.7.0->snowflake) (2024.2.2)\n",
      "Requirement already satisfied: filelock<4,>=3.5 in c:\\users\\kaustubhgupta\\anaconda3\\lib\\site-packages (from snowflake-connector-python<4.0.0,>=3.6.0->snowflake-snowpark-python<2.0.0,>=1.5.0->snowflake-core==0.7.0->snowflake) (3.13.1)\n",
      "Requirement already satisfied: sortedcontainers>=2.4.0 in c:\\users\\kaustubhgupta\\anaconda3\\lib\\site-packages (from snowflake-connector-python<4.0.0,>=3.6.0->snowflake-snowpark-python<2.0.0,>=1.5.0->snowflake-core==0.7.0->snowflake) (2.4.0)\n",
      "Requirement already satisfied: platformdirs<4.0.0,>=2.6.0 in c:\\users\\kaustubhgupta\\anaconda3\\lib\\site-packages (from snowflake-connector-python<4.0.0,>=3.6.0->snowflake-snowpark-python<2.0.0,>=1.5.0->snowflake-core==0.7.0->snowflake) (3.10.0)\n",
      "Requirement already satisfied: tomlkit in c:\\users\\kaustubhgupta\\anaconda3\\lib\\site-packages (from snowflake-connector-python<4.0.0,>=3.6.0->snowflake-snowpark-python<2.0.0,>=1.5.0->snowflake-core==0.7.0->snowflake) (0.11.1)\n",
      "Requirement already satisfied: pycparser in c:\\users\\kaustubhgupta\\anaconda3\\lib\\site-packages (from cffi<2.0.0,>=1.9->snowflake-connector-python<4.0.0,>=3.6.0->snowflake-snowpark-python<2.0.0,>=1.5.0->snowflake-core==0.7.0->snowflake) (2.21)\n",
      "Downloading snowflake-0.7.0-py3-none-any.whl (1.5 kB)\n",
      "Downloading snowflake_core-0.7.0-py3-none-any.whl (330 kB)\n",
      "   ---------------------------------------- 0.0/330.1 kB ? eta -:--:--\n",
      "   ------------- -------------------------- 112.6/330.1 kB 6.4 MB/s eta 0:00:01\n",
      "   ------------------------------- -------- 256.0/330.1 kB 3.2 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 330.1/330.1 kB 2.6 MB/s eta 0:00:00\n",
      "Downloading snowflake_legacy-0.7.0-py3-none-any.whl (3.1 kB)\n",
      "Downloading atpublic-4.1.0-py3-none-any.whl (5.0 kB)\n",
      "Downloading snowflake_snowpark_python-1.14.0-py3-none-any.whl (419 kB)\n",
      "   ---------------------------------------- 0.0/419.7 kB ? eta -:--:--\n",
      "   --------------------------------------  409.6/419.7 kB 12.5 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 419.7/419.7 kB 6.5 MB/s eta 0:00:00\n",
      "Downloading snowflake_connector_python-3.7.1-cp311-cp311-win_amd64.whl (910 kB)\n",
      "   ---------------------------------------- 0.0/910.4 kB ? eta -:--:--\n",
      "   ------ --------------------------------- 143.4/910.4 kB ? eta -:--:--\n",
      "   ------ --------------------------------- 143.4/910.4 kB ? eta -:--:--\n",
      "   ---------------------------------------  901.1/910.4 kB 8.1 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 910.4/910.4 kB 7.2 MB/s eta 0:00:00\n",
      "Downloading asn1crypto-1.5.1-py2.py3-none-any.whl (105 kB)\n",
      "   ---------------------------------------- 0.0/105.0 kB ? eta -:--:--\n",
      "   ---------------------------------------- 105.0/105.0 kB 3.1 MB/s eta 0:00:00\n",
      "Installing collected packages: asn1crypto, snowflake-legacy, atpublic, snowflake-connector-python, snowflake-snowpark-python, snowflake-core, snowflake\n",
      "Successfully installed asn1crypto-1.5.1 atpublic-4.1.0 snowflake-0.7.0 snowflake-connector-python-3.7.1 snowflake-core-0.7.0 snowflake-legacy-0.7.0 snowflake-snowpark-python-1.14.0\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install snowflake"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f8b70a10-e24e-413b-9dc4-197fc7dd8a99",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
